# Generated by Django 5.1.7 on 2025-04-06 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_carservice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CarEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("trn_number", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=20)),
                ("emirate", models.CharField(max_length=50)),
                ("mobile_no", models.CharField(max_length=20)),
                ("estimate_number", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("ref_number", models.CharField(blank=True, max_length=100, null=True)),
                ("est_days", models.IntegerField(default=0)),
                ("payment_terms", models.TextField(blank=True)),
                ("registration", models.CharField(max_length=100)),
                ("make_model", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("chassis_no", models.CharField(max_length=100)),
                ("km_miles", models.CharField(max_length=50)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("net_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("vat", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "total_incl_vat",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
